version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "docker"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
